### PR TITLE
Fix/checkbox data loading on anc

### LINKED ISSUE #149: ANC Visit
After recording a client's visit for ANC, when clicking the button for editing the visit, the action is blank. And, only one action is loaded.

### PR DESCRIPTION
**Pull request by dev-billy**

### CODE REVIEW

**Comment by zk497** [comment]
@dev-billy, I noticed an issue while I was testing. I only filled and completed the first action and it is shown in the below screenshot. 
Screenshot_1657701029

When I get back to edit, the actions load correctly. However, as you can see from the below screenshot, some of the actions that I did not fill in at all such as Family Planning, Counselling, Malaria Prevention, and Remarks/Comments have their subtitle messages displayed. 

Screenshot_1657701040

**Comment by dev-billy** [comment]
I think the bug here is how you saved the form with only one action filled, I think in ANC community only the remarks/comments is the optional action
Let me give it a look though

**Comment by zk497** [comment]
@dev-billy Alright, sure.

**Comment by dev-billy** [comment]
@zk497  this [d91219e](https://github.com/SoftmedTanzania/opensrp-client-chw/pull/153/commits/d91219e4b1155a022802c9b987c1013168045041) fixes the issue with saving when actions are not valid, can you verify if this still works?

**Comment by zk497** [comment]
@dev-billy Sure, let me check it out.

**Comment by zk497** [comment]
@dev-billy I'm still facing the same issue. 

Screenshot_1657707365

**Comment by dev-billy** [comment]
Is this a new visit or are you editing the one from before?

**Review by cozej4 — APPROVED** [review]

**Pull request merged**
